### ISSUE TITLE
IP address and port used for a node

### ISSUE THREAD

**Issue by suokunlong** [VoiNetwork/voi-swarm#34]
Hi, I want to run a node, but my server has a dynamic public IP address and the ports 80/8080/443 are not available to the public. As a result, I want to know:
1. Does the chain find each other based on domain names or IP address? If the IP address is dynamic while the domain name is always accessible to the public as I have a dynamic dns, is that ok?
2. What ports does voi swarm and the chain use? If I have a firewall configured in my system, then which ports should I enable?

Thank you in advance.

**Comment by hsoerensen** [comment]
This is best handled in Discord in the #node-runners channel.

https://discord.com/invite/voi-network
