### ISSUE TITLE
Account Not Found get error  / goal-node-status

### ISSUE THREAD

**Issue by strdex** [VoiNetwork/voi-swarm#41]
get_accounts() {
  if execute_sudo 'test ! -f "/var/lib/voi/algod/data/voitest-v1/accountList.json"'; then
    util_abort "Account list not found. Exiting the program."
  fi

  accounts_json=$(execute_sudo 'cat /var/lib/voi/algod/data/voitest-v1/accountList.json')
  number_of_accounts=$(echo "${accounts_json}" | jq '.Accounts | length')

  if [[ $number_of_accounts -eq 0 ]]; then
    return 1
  fi

  account_addresses=$(echo "$accounts_json" | jq -r '.Accounts | keys[]')
  echo "${account_addresses}"
}

"voitest-v1"  to replace "voimain-v1.0"

Account not found in get error  goal-node-status scrprit 

via  Resplined@DG

**Comment by hsoerensen** [comment]
Fixed in https://github.com/VoiNetwork/voi-swarm/commit/3814b6c785725aa9de7a5544bb38850cb4152268
